apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fnb-os-web-env
  namespace: apps
spec:
  encryptedData:
    GEMINI_API_KEY: AgAvcaHLfUEU+LcQxo1ZaEpuU8YTGhy9sABFBXt2ny/E0F8s+7yPrwV/xC8hy08AceyUxW0HWJChhRqm6NpBpWo7I5Lxg64kt0ygi+Q02MVcVhzgm6eV3PXZEYviMKIIH0>
    NEXT_PUBLIC_APP_URL: AgAfye/Vi0YX2M6WS661nefBOOSeJiMivgcMhYsHfDRTMtV5J7hE7Vgyt4T2TeV7ptgwWXrZ73trdYAW/4CFF5EU317xJ+fRG8i5BpO/W8C2u8cxJx6zZfkxNhmC+>
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: AgBgeVJ/rqcRxHxKC5AZUzLg6B28jycgio7Z86QrnBp+oo5yfsCWamSl/pX3+s4pgJful+zE0OSNHUyz8MPvpKqBHCY0y9d379E/>
    NEXT_PUBLIC_SUPABASE_URL: AgAxTWdk8y5t78AVsXaAPCq+IBWdECXQfy9tc/fd0l9vexTvVFSVfaAfjMWSuLGn4qJzODJkwBcvobO+agodxymOTLmyDc5OM89o4e3lMsmQFH9wqVmMqMXK>
  template:
    metadata:
      name: fnb-os-web-env
      namespace: apps
